# Generated by Django 5.0.4 on 2024-05-08 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='deslike',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='like',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
