# Generated by Django 5.0.4 on 2024-05-10 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_alter_like_deslike_alter_like_like'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='deslike',
        ),
        migrations.RemoveField(
            model_name='like',
            name='like',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.AddField(
            model_name='like',
            name='users',
            field=models.ManyToManyField(related_name='evaluation_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='like',
            name='evaluation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='movie.evaluation'),
        ),
        migrations.CreateModel(
            name='Dislike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dislikes', to='movie.evaluation')),
                ('users', models.ManyToManyField(related_name='evaluation_dislikes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
