# Generated by Django 5.0.7 on 2024-08-04 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_remove_like_deslike_remove_like_like_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(blank=True, upload_to='movies/images/'),
        ),
    ]
