# Generated by Django 5.0.7 on 2024-09-13 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_alter_evaluation_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='url',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
